version: 2
jobs:
  build:
    docker:
      - image: cypress/base

    steps:
      - checkout

      - run:
          name: Setup
          command: yarn install

      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - node_modules

      - run:
          name: Linters
          command: yarn lint

      - run:
          name: Unit Tests
          command: |
            yarn test --coverage
            codecov < ./coverage/lcov.info || true

      - run:
          name: Integration Tests
          command: yarn cypress

      - run:
          name: Build
          command: yarn build

  publish:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}

      - run:
          name: Publish
          command: yarn deploy:prod

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: dev
