version: 2
  jobs:
    build:
      docker:
        - image: circleci/node:latest
      steps:
        - checkout

        - run: 
          name: Setup
          command: yarn install

        - run: 
          name: Linters
          command: yarn lint
       
        - run: 
          name: Tests
          command: |
            yarn test --coverage
            codecov < ./coverage/lcov.info || true