version: 2
jobs:
  build:
    docker:
      - image: cypress/base

    steps:
      - checkout

      - run:
          name: Setup
          command: yarn install

      - run:
          name: Linters
          command: yarn lint

      - run:
          name: Unit Tests
          command: |
            yarn test --coverage --passWithNoTests
            codecov < ./coverage/lcov.info || true

      - run:
          name: Integration Tests
          command: |
            yarn cypress
            codecov < ./coverage/lcov.info || true

      - run:
          name: Build
          command: yarn build

  publish:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Publish
          command: echo 'Published'

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
