version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Setup
          command: yarn install

      - run:
          name: Linters
          command: yarn lint

      - run:
          name: Unit Tests
          command: |
            yarn test --coverage --passWithNoTests
            codecov < ./coverage/lcov.info || true

      - run:
          name: Integration Tests
          command: |
            yarn cypress
            codecov < ./coverage/lcov.info || true
